"""initial_schema

Revision ID: d6edeab50de2
Revises: 
Create Date: 2026-01-05 04:03:09.787250+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd6edeab50de2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poll_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('events_found', sa.Integer(), nullable=False),
    sa.Column('new_events', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_poll_runs_started_at', 'poll_runs', ['started_at'], unique=False, postgresql_using='btree')
    op.create_index('ix_poll_runs_status', 'poll_runs', ['status'], unique=False, postgresql_using='btree')
    op.create_table('ofac_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('poll_run_id', sa.UUID(), nullable=True),
    sa.Column('event_hash', sa.String(length=64), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('published_date', sa.Date(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('is_venezuela_related', sa.Boolean(), nullable=False),
    sa.Column('is_chevron_related', sa.Boolean(), nullable=False),
    sa.Column('keywords_matched', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['poll_run_id'], ['poll_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_hash')
    )
    op.create_index('ix_events_first_seen', 'ofac_events', ['first_seen_at'], unique=False, postgresql_using='btree')
    op.create_index('ix_events_hash', 'ofac_events', ['event_hash'], unique=True)
    op.create_index('ix_events_published', 'ofac_events', ['published_date'], unique=False, postgresql_using='btree')
    op.create_index('ix_events_venezuela', 'ofac_events', ['is_venezuela_related'], unique=False, postgresql_where='is_venezuela_related = true')
    op.create_table('ofac_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('poll_run_id', sa.UUID(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('raw_html', sa.Text(), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['poll_run_id'], ['poll_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_snapshots_content_hash', 'ofac_snapshots', ['content_hash'], unique=False, postgresql_using='btree')
    op.create_index('ix_snapshots_poll_run', 'ofac_snapshots', ['poll_run_id'], unique=False, postgresql_using='btree')
    op.create_table('alert_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('rule_matched', sa.Text(), nullable=False),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['ofac_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alerts_event', 'alert_log', ['event_id'], unique=False, postgresql_using='btree')
    op.create_index('ix_alerts_type', 'alert_log', ['alert_type'], unique=False, postgresql_using='btree')
    op.create_index('ix_alerts_unacked', 'alert_log', ['acknowledged'], unique=False, postgresql_where='acknowledged = false')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_alerts_unacked', table_name='alert_log', postgresql_where='acknowledged = false')
    op.drop_index('ix_alerts_type', table_name='alert_log', postgresql_using='btree')
    op.drop_index('ix_alerts_event', table_name='alert_log', postgresql_using='btree')
    op.drop_table('alert_log')
    op.drop_index('ix_snapshots_poll_run', table_name='ofac_snapshots', postgresql_using='btree')
    op.drop_index('ix_snapshots_content_hash', table_name='ofac_snapshots', postgresql_using='btree')
    op.drop_table('ofac_snapshots')
    op.drop_index('ix_events_venezuela', table_name='ofac_events', postgresql_where='is_venezuela_related = true')
    op.drop_index('ix_events_published', table_name='ofac_events', postgresql_using='btree')
    op.drop_index('ix_events_hash', table_name='ofac_events')
    op.drop_index('ix_events_first_seen', table_name='ofac_events', postgresql_using='btree')
    op.drop_table('ofac_events')
    op.drop_index('ix_poll_runs_status', table_name='poll_runs', postgresql_using='btree')
    op.drop_index('ix_poll_runs_started_at', table_name='poll_runs', postgresql_using='btree')
    op.drop_table('poll_runs')
    # ### end Alembic commands ###
